### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Joe-Brason** [ITSLeeds/TDS#111]
In the [TDS/coursework-template.md](https://github.com/ITSLeeds/TDS/blob/master/coursework-template.md#04-marks) file, there is a spelling error in the section '0.4 Marks', in point 13. 'tranferred' should presumably be 'transferred' (missing an 's')

**Comment by Robinlovelace** [comment]
Correct, that looks like a typo. If you'd like to fix it, check out the source code that generates that file here: https://github.com/ITSLeeds/TDS/blob/master/coursework-template.Rmd
