### ISSUE TITLE
Safe_cast

### ISSUE THREAD

**Issue by nujcharee** [ITSLeeds/TDS#17]
Hi
During the course I seemed to remember you mentioned an argument safe_cast but I can’t quite remember what context or what function that it refers to - please could you correct me if I’m wrong? Thank you so much

**Comment by Robinlovelace** [comment]
Hi @nujcharee thanks for the question and sorry for the slow reply. Time flies! I think it likely [`st_cast()`](https://r-spatial.github.io/sf/reference/st_cast.html) that I was referring to. Does that sound plausible? All the best!
