### ISSUE TITLE
Try setting-up open instance of OTP for Leeds/West Yorkshsire/Isle of Wight

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/TDS#20]
Please share set-up code.

**Comment by Robinlovelace** [comment]
Heads-up @mem48

**Comment by Robinlovelace** [comment]
Great news, seems to be working: 
![image](https://user-images.githubusercontent.com/1825120/73352588-5a3b2600-4289-11ea-93f0-2f296cd364c1.png)

**Comment by Robinlovelace** [comment]
Heads-up @mem48 have you had a chance to look at getting the GTFS layer working?

**Comment by mem48** [comment]
I've been trying but so far with no success. It is odd because the GTFS file is valid, and is being imported into OpenTripPlanner. So why the routes are missing is a bit of a mystery.

**Comment by Robinlovelace** [comment]
Hmmm, maybe we could demo it for a different region. The process may help uncover the bug in the GTFS conversion... It would be amazing if we could do an international example, e.g. building on the data here: https://itsleeds.github.io/pct/articles/pct-international.html

**Comment by mem48** [comment]
Now fixed and working with new gtfs data set. Problem was mistaken 0 or 1, 0 means you can board the train, but I set to 1. This meant the GTFS loaded correctly but you were almost never allowed to board a train

**Comment by mem48** [comment]
@Robinlovelace the server is down!

**Comment by Robinlovelace** [comment]
Working again now, as shown below (with slightly different hostname):

``` r

library(opentripplanner)
library(tmap)
tmap_mode("view")
#> tmap mode set to interactive viewing
otpcon = otp_connect(hostname = "86.6.99.9", port = 8080) # To connect to robin's instance
#> Router http://86.6.99.6:8080/otp/routers/default exists

route_walk = otp_plan(otpcon, 
                  fromPlace = c(-1.63078, 53.84675), 
                  toPlace = c(-1.59499, 53.81743), mode = "WALK")

route_walk = otp_plan(otpcon, 
                      fromPlace = c(-1.63078, 53.84675), 
                      toPlace = c(-1.59499, 53.81743), mode = "WALK")

route_transit = otp_plan(otpcon, 
                  fromPlace = c(-1.63078, 53.84675), 
                  toPlace = c(-1.59499, 53.81743), mode = c("WALK","TRANSIT"))


qtm(sf::st_zm(route_transit), lines.col = "mode", lines.lwd = 3)
#> Linking to GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1
```

![](https://i.imgur.com/0vHiG93.png)

<sup>Created on 2020-02-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
