### ISSUE TITLE
Enabling better reproducibility

### ISSUE THREAD

**Issue by mrzeyyyyy** [ITSLeeds/TDS#30]
Hello Robin, 

Your instructions stated that the .zip file should contain the minimal amount of dataset required to reproduce the results. As I was working through my code, there are many chunks where several lines were written to produce figures (e.g. graphs). I'd save them as "figure_1.png", "figure_2.png" etc. 

Then, I choose to "switch off" that code chunk because I do not want to run those code chunks everytime I knit them. Instead, as you've suggested, I use the include_graphic("figure_1.png") function to read in the .png file whenever I knit them. It's much more computationally efficient that way.

Hence, in addition to the datasets, I would imagine that you would also require those .png files (which we have saved) in the zip file to be submitted, to allow you to reproduce the code in our .Rmd file successfully without errors?

**Comment by Robinlovelace** [comment]
Hi @mrzeyyyyy thanks for the question. Yes, if `.png` files are required to reproduce the report they should be in the submitted .zip file. Does that answer your question?

An approach to ensure reproducibility while reducing report compile times is to start with a small sample of the data, that can also be included in the zip file.

**Comment by mrzeyyyyy** [comment]
Yes, thanks @Robinlovelace. Got it. Thanks!

**Comment by Robinlovelace** [comment]
Great, I will close this issue now.
