### ISSUE TITLE
How to make boxplots

### ISSUE THREAD

**Issue by Joe618** [ITSLeeds/TDS#31]
Dear Robin, 

Could you teach me how to make the below boxplots? It can show double x coordinates and can show double boxplots in the same category.
<img width="851" alt="截屏2020-04-30上午12 54 59" src="https://user-images.githubusercontent.com/57900043/80700136-18628b80-8ad5-11ea-921b-49a307122a85.png">

Thanks in advance 

Binghong

**Comment by Robinlovelace** [comment]
Hi Binghong, good question. Can you try reproducing the examples here?: https://ggplot2.tidyverse.org/reference/geom_boxplot.html#examples

That will be a good starting point I think.
