### ISSUE TITLE
change variable mode

### ISSUE THREAD

**Issue by mm19tz** [ITSLeeds/TDS#33]
I import data by read.csv and R treat Date(dd/mm/yyyy) as numeric,how can I convert it to date? I try as.date but it does not work.

> dd<-read.csv("Camera_data.csv")
> mode(dd$Date)
[1] "numeric"
> dd$Date<-as.Date(dd$Date)

**Comment by Robinlovelace** [comment]
Good question @mm19tz, can you provide a reproducible example? I will try to create a reproducible exmaple below...

**Comment by Robinlovelace** [comment]
Here is a reproducible demonstration of converting to and from date and numeric modes:

``` r

date_character = "2020-05-06"
date_date = as.Date(date_character)
date_numeric = as.numeric(date_date)
date_numeric
#> [1] 18388
as.Date(date_numeric, origin = "1970-01-01")
#> [1] "2020-05-06"
```

<sup>Created on 2020-05-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
