### ISSUE TITLE
Spatial joins

### ISSUE THREAD

**Issue by zeyalt** [ITSLeeds/TDS#34]
Hello Robin, 

I was wondering if you can explain a little how `st_is_within_dist()` works, if I were to use that to join points data to line data. Does it do the join based on the distance from the point to the nearest location along the linestring, or to the centroid of the linestring?

Thanks!

**Comment by Robinlovelace** [comment]
Hi @mrzeyyyyy good question. I can best answer it with links I think:

- General description of spatial joins: https://geocompr.robinlovelace.net/spatial-operations.html#spatial-joining
- Looking for a link regarding the second question, I'm confident it's the distance to *any point* in the other spatial object.

**Comment by zeyalt** [comment]
Thank you, Robin.
