### ISSUE TITLE
link cannot be accessed

### ISSUE THREAD

**Issue by Joe618** [ITSLeeds/TDS#35]
Hi Robin,

The below link cannot be accessed and have warning said that it is not a safe link.

UK census data can be accessed from several places including: https://census.edina.ac.uk/bds.html https://www.nomisweb.co.uk/census/2011

So do you have an alternative link or do you have other resources to find the data of West Yorkshire including GDP, resident density, average income of this region, etc..

Thanks in advance.

Binghong Zou

**Comment by Robinlovelace** [comment]
Hi Binghong, no I do not have other resources on GDP, resident density etc. I did show you how to get data with estimates of population here: https://github.com/ITSLeeds/TDS/issues/28#issuecomment-602740808

So closing this issue for now.
