### ISSUE TITLE
Page limit or word limit

### ISSUE THREAD

**Issue by zeyalt** [ITSLeeds/TDS#38]
Hello Robin, 

I was about to upload my coursework on Minerva through the submission widget when I saw the heading “TRAN5340M 3000 Word Project due in Friday 29th May by 2pm”. I understood from your email regarding coursework guidance on 4 March 2020 that the limit is 10 pages. You've recently clarified that it's 10 pages excluding Appendix and References. Can I check if the 3000-word limit still applies for us then? Based on the pdf template output from R Markdown, a 10-page report would go way beyond 3000 words. Mine's a 10-page report with about 5400 words now. It would be a waste for me to cut almost half of my current draft if the 3000-word limit does apply.

**Comment by Robinlovelace** [comment]
Hi @zeyalt, good question. I confirm that there is no word count, the only limit is the 10 page limit on the .pdf document. Apologies for the confusion.

**Comment by zeyalt** [comment]
That's great! Thanks Robin.
