### ISSUE TITLE
Creating inset maps

### ISSUE THREAD

**Issue by Emily181** [ITSLeeds/TDS#39]
Hi, I am attempting to show a map of London. However the more interesting parts lie within the center. I wanted to create an inset map, and have attempted as follows but the image/map of the whole of London is too large for the box. I've tried adjusting parameters to no success. I also don't like the way I am "zooming into" the center, I would prefer another method, selecting the central square.

Can you spot where I may have gone wrong? Or perhaps suggest how I can subset the map to just reveal the central square? (The following image includes all the additional information I have put in my own code)

```{r, eval = FALSE}
library(pct)
library(tidyverse)
library(dplyr)
library(grid)

district_pct = pct::get_pct_zones(region = "london")
local_authority_pct = district_pct %>%
group_by(lad_name) %>%
dplyr::summarise(
bicycle = sum(bicycle)
)
main_map = tm_shape(la_pa)+
  tm_polygons()

central_london = c("City of London", "Camden", "Islington", "Hackney", "Tower Hamlets", "Southwark","Lambeth", "Westminster")
central_la = filter(la_pa, local_authority_district %in% central_london)
central_map = tm_shape(central_la)+
  tm_polygons()

viewport_bxl = viewport(x = 0, y = 0, width = 1, height = 1, xscale = c(0,1), yscale = c(0,1))

tmap_save(central_map, filename = 'attempt.png', width = 800, height = 800
          insets_tm = main_map, insets_vp = viewport_bxl)
```
![attempt7](https://user-images.githubusercontent.com/60652564/82307203-ee0b3c00-99b7-11ea-8cc3-b6f6756dcca7.png)

**Comment by Robinlovelace** [comment]
Hi @Emily181, thanks for the question and a great code example to show what you've done. First response: I'm not sure sorry, but I can provide some pointers to good resources. To do inset maps with tmap, this may be of use/interest (apologies if you've already been looking at this): https://geocompr.robinlovelace.net/adv-map.html#inset-maps

Looking at your code, I wonder if it's related to the arguments you pass to `viewport()`?

In that section it uses smaller values of `width` and `height`.

```
print(nz_map, vp = viewport(0.8, 0.27, width = 0.5, height = 0.5))
```

There's also a good response here: https://stackoverflow.com/questions/42086603/producing-an-inset-map-with-the-tmap-package-in-r


There's a blog post on inset maps with ggplot2 here: https://geocompr.github.io/post/2019/ggplot2-inset-maps/

Does that help?
