### ISSUE TITLE
Update timetable for 2020-21 

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/TDS#45]

**Comment by Robinlovelace** [comment]
http://timetable.leeds.ac.uk/teaching/202021/reporting/Individual?objectclass=module&idtype=name&identifier=TRAN5340M01&&template=SWSCUST+module+Individual&days=1-7&weeks=1-52&periods=1-21

**Comment by Robinlovelace** [comment]
Heads-up @mem48 I've just timetabled this. See the commit above in case you're interested in how to get reproducible timetabling in R, could be more automated but much more reproducible than the systems that UoL use! I plan to invite you to the sessions you're pencilled in for. Note: your routing lecture will be a pre-record, we're doing the online sessions focused on questions.

**Comment by mem48** [comment]
Thanks for the heads up, recording the lecture shouldn't be a problem but it will be a shame to loose the interactive parts.

**Comment by Robinlovelace** [comment]
> Thanks for the heads up, recording the lecture shouldn't be a problem but it will be a shame to loose the interactive parts.

Yes, although there will be seminars and workshops aplenty, including the routing workshop: https://github.com/ITSLeeds/TDS/blob/master/timetable-2020.csv

**Comment by mem48** [comment]
@Robinlovelace the routing pratical is before the lecture, seems like that is a mistake?

**Comment by Robinlovelace** [comment]
Aha yes...

**Comment by Robinlovelace** [comment]
Thanks for pointing this out @mem48. The updated timetable has the routing practical 10 days after the lecture. There are other options that I considered but I think that's an acceptable compromise given the cards I was handed with the timetable. Is that OK for you? Cheers.

**Comment by mem48** [comment]
Yes that's much better

**Comment by Robinlovelace** [comment]
Good agile workflow, thanks for identifying and flagging the issue early :+1:
