### ISSUE TITLE
Unable to download library spDataLarge on R version 4.0.3

### ISSUE THREAD

**Issue by ekta-aggarwal54** [ITSLeeds/TDS#50]
While going through chapter 12 I am unable to install the library: spDataLarge.
I am receiving the following error:
 
Warning in install.packages :
  package ‘spDataLarge’ is not available for this version of R
 
A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by Robinlovelace** [comment]
Good question @ekta-aggarwal54, thanks for opening the issue - I suspect others will be wondering the same thing.

Have you tried executing the following lines of code?

```r
install.packages("remotes")
remotes::install_github("nowosad/spDataLarge")
```

That may help.

**Comment by ekta-aggarwal54** [comment]
Unfortunately I am still receiving the following error:
![spdatalarge_error](https://user-images.githubusercontent.com/26125667/107616453-1fc5e080-6c74-11eb-89e9-69f91faf49c9.JPG)
