### ISSUE TITLE
My changes are not being reflected in locations.csv

### ISSUE THREAD

**Issue by ekta-aggarwal54** [ITSLeeds/TDS#63]
Hi Robin, 
I tried adding my location coordinates to locations.csv and have clicked propose file change, but am still unable to view the changes made by me. ( I tried this twice) . Can you help?

**Comment by Robinlovelace** [comment]
You need to follow *all* the steps to open a PR. Try following the instructions here: https://guides.github.com/activities/hello-world/#commit
