### ISSUE TITLE
Error while sourcing "https://git.io/JvGjF" and installing "ITSleeds/geofabrik"

### ISSUE THREAD

**Issue by ekta-aggarwal54** [ITSLeeds/TDS#69]
Hi I am facing the following error while installing and sourcing the following: 
![sourcing_geofabrik_error](https://user-images.githubusercontent.com/26125667/108335451-fae3e700-71f8-11eb-8676-70d959366dd9.JPG)

**Comment by Robinlovelace** [comment]
Hi @ekta-aggarwal54 I think there is a bug in those checks. Heads-up @mem48 can you take a look?

**Comment by mem48** [comment]
Thats odd as geofabrik is not one of the packages listed anymore. Sounds like a caching problem.

**Comment by mem48** [comment]
@ekta-aggarwal54 can you 

1. Restart R
2. Open the url in a web browser
3. Copy the code and run it in R.


You should see code like this:

```
# Settings - can be changed source("https://github.com/ITSLeeds/go/releases/download/v0.3/setup_function.R") setup_R(pkgs = c("sf", "tidyverse", "tmap", "pct", "stats19", "stplanr", "dodgr", "geodist", "opentripplanner", "igraph", "mapview", "osmextract", "nycflights13", "snakecase"), pkgs_gh = c("luukvdmeer/sfnetworks@0.4.1", "nowosad/spDataLarge", "ITSLeeds/od", "a-b-street/abstr")) rm(setup_R)
```

**Comment by mem48** [comment]
I think this is now fixed
