### ISSUE TITLE
Error in otp_build_graph in opentripplanner

### ISSUE THREAD

**Issue by ekta-aggarwal54** [ITSLeeds/TDS#70]
Hi While running the code mentioned in the  OpenTripPlanner package paper 
![opentripplanner_error](https://user-images.githubusercontent.com/26125667/108336600-3af79980-71fa-11eb-8fea-ffc80e74ab1b.JPG)

**Comment by Robinlovelace** [comment]
Hi @ekta-aggarwal54 I think you need to have OTP running on your computer for that to work. Do the first lines of code here work OK for you?: https://github.com/ITSLeeds/TDS/blob/master/practicals/6-routing.md#setting-up-10-minutes

We have set up a server here at otp.saferactive.org

Note: this practical is not happening until next week but good that you're ahead of the game and testing the install.

**Comment by mem48** [comment]
@ekta-aggarwal54 top marks for enthusiasm but I've been making some updates to the practical and have not yet tested it.  So there may be some bugs.

But you seem to be building a local version of Opentripplanner in which case check the package documents
