### ISSUE TITLE
Can't install stplanr

### ISSUE THREAD

**Issue by mem48** [ITSLeeds/TDS#83]
@Robinlovelace I'm going to have to revert the changes you made to the routing pratical. I can't install the new version of stplanr sucesfully because of a dependance on terra >= 1.5.12 which is not compiling on windows. 

```
library(stplanr)    # General transport data functions
Error: package or namespace load failed for ‘stplanr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘terra’ 1.4-22 is being loaded, but >= 1.5.12 is required
```

**Comment by Robinlovelace** [comment]
@mem48 thanks for the heads-up. We hit this problem last week and found a solution that worked for everyone who tried it. Try this: 

```
install.packages('terra', repos='https://rspatial.r-universe.dev')
```

**Comment by mem48** [comment]
I'll try it when I get back. In the meantime the practical works without stplanr

**Comment by Robinlovelace** [comment]
> I'll try it when I get back. In the meantime the practical works without stplanr

When do you get back?

**Comment by mem48** [comment]
This is not working for me, I'm keeping the practial without stplanr as I can't teach it if I can't run it.

**Comment by Robinlovelace** [comment]
> This is not working for me, I'm keeping the practial without stplanr as I can't teach it if I can't run it.

Sorry to hear you're still having issues. What error message do you get?

**Comment by Robinlovelace** [comment]
Heads-up @mem48 planned solution to this: push a copy of the practical with the updated route function to give max flexibility for the students who want to. Then we can replace the old way with the new way after the practical.
