### ISSUE TITLE
Practical -3 Error message on below code chunk

### ISSUE THREAD

**Issue by ketchupdatacommit** [ITSLeeds/TDS#86]
```
> library(osmdata)
> data_osm = opq("leeds uk") %>% 
>   add_osm_feature(key = "name", value = "Cycle Superhighway 1") %>% 
>   osmdata_sf()
```

Throws the error : "**Error: Overpass query unavailable without internet"**

The quick  solution found on SO was to add the following lines of code to the above chunk

```
> `assign("has_internet_via_proxy", TRUE, environment(curl::has_internet))`

```

**Comment by Robinlovelace** [comment]
Many thanks for opening this issue. Although it is fixed I will leave it open here for the benefit of others, great to see a full reproducible example!
